Afp:
    type: entity
    table: afp
    id:
        idAfp:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_afp
            generator:
                strategy: IDENTITY
    fields:
        afp:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
