EstadoTelefono:
    type: entity
    table: estado_telefono
    id:
        idEstadoTelefono:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_estado_telefono
            generator:
                strategy: IDENTITY
    fields:
        estadoTelefono:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: estado_telefono
    lifecycleCallbacks: {  }
