GestionHcab:
    type: entity
    table: gestion_hcab
    indexes:
        fk_prospecto_has_usuario_usuario1_idx:
            columns:
                - id_usuario
        fk_prospecto_has_usuario_prospecto1_idx:
            columns:
                - id_prospecto
        fk_gestion_historico_periodo1_idx:
            columns:
                - periodo
        fk_gestion_historico_producto1_idx:
            columns:
                - id_producto
        fk_gestion_historico_afp1_idx:
            columns:
                - id_afp
        fk_gestion_hcab_proceso_etapa1_idx:
            columns:
                - id_proceso_etapa
        fk_gestion_hcab_proceso_resultado1_idx:
            columns:
                - id_proceso_resultado
    id:
        idDetalle:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_detalle
    fields:
        fechaHora:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_hora
        fechaGestion:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_gestion
        fechaSiguiente:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_siguiente
        motivo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        monto:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
    oneToOne:
        idProspecto:
            targetEntity: Prospecto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_prospecto:
                    referencedColumnName: id_prospecto
            orphanRemoval: false
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        periodo:
            targetEntity: Periodo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                periodo:
                    referencedColumnName: periodo
            orphanRemoval: false
        idProducto:
            targetEntity: Producto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_producto:
                    referencedColumnName: id_producto
            orphanRemoval: false
        idProcesoEtapa:
            targetEntity: ProcesoEtapa
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_proceso_etapa:
                    referencedColumnName: id_proceso_etapa
            orphanRemoval: false
        idProcesoResultado:
            targetEntity: ProcesoResultado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_proceso_resultado:
                    referencedColumnName: id_proceso_resultado
            orphanRemoval: false
    manyToOne:
        idAfp:
            targetEntity: Afp
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_afp:
                    referencedColumnName: id_afp
            orphanRemoval: false
    lifecycleCallbacks: {  }
