TipoTelefono:
    type: entity
    table: tipo_telefono
    id:
        idTipoTelefono:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_tipo_telefono
            generator:
                strategy: IDENTITY
    fields:
        tipoTelefono:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: tipo_telefono
    lifecycleCallbacks: {  }
