TipoDocumento:
    type: entity
    table: tipo_documento
    id:
        idTipdoc:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_tipdoc
            generator:
                strategy: IDENTITY
    fields:
        tipoDocumento:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: tipo_documento
    lifecycleCallbacks: {  }
